name: main-workflow
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: zip AWSConsoleNavigator.zip img/Region_dark-bg\@4x.png background.js CONTRIBUTING.md LICENSE manifest.json popup.css popup.html popup.js README.md
