name: Run tests
on:
  push:
    branches-ignore:
      - main
jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: npm install && npm test
